import { getLang } from '../../lib/i18n.js';

// User-facing copy lives here so renderer labels can change language without
// touching pipeline IDs, paths, commands, blocker codes, or persisted payloads.
const KO = Object.freeze({
    // Navigation and shared shell
    'Planning': '기획',
    'Production prep': '제작 준비',
    'Generation and review': '생성·검토',
    'Finishing': '마무리',
    'Project': '프로젝트',
    'Storyboard': '스토리보드',
    'Shot design': '샷 설계',
    'Motion board': '모션 보드',
    'Reference images': '참조 이미지',
    'Prompt packs': '프롬프트 팩',
    'Review gates': '검토 게이트',
    'Generation queue': '생성 대기열',
    'Clip QA': '클립 QA',
    'Final edit': '최종 편집',
    'Settings': '설정',
    'Project overview': '프로젝트 개요',
    'Shot Design': '샷 설계',
    'Motion Board': '모션 보드',
    'First Frames And References': '첫 프레임·참조 이미지',
    'Prompt Packs': '프롬프트 팩',
    'Review Gates': '검토 게이트',
    'Generation Queue': '생성 대기열',
    'Clip QA And Accepted Ranges': '클립 QA·채택 구간',
    'Final Edit And Report': '최종 편집·보고서',
    'Pipeline Settings': '파이프라인 설정',
    'Pipeline workflow steps': '파이프라인 작업 단계',
    'Choose a workflow step': '작업 단계 선택',
    'Productions': '제작 목록',
    'Production list': '제작 목록',
    'Open production folder': '제작 폴더 열기',
    'Refresh productions': '목록 새로고침',
    'New project draft': '새 프로젝트 초안',
    'Refresh production list': '제작 목록 새로고침',
    'Open settings': '설정 열기',
    'Scanning…': '검색 중…',
    'Scanning production parent…': '제작 상위 폴더를 검색하는 중입니다…',
    'Error': '오류',
    'Empty': '비어 있음',
    'No productions found. Set a production parent in Settings.': '제작 폴더를 찾지 못했습니다. 설정에서 제작 상위 폴더를 지정하세요.',
    'Cannot read parent: {reason}': '상위 폴더를 읽을 수 없습니다: {reason}',
    'just now': '방금 전',
    '{count} files': '파일 {count}개',
    'brief: {value}': '브리프: {value}',
    'ledger: {value}': '원장: {value}',
    '{count}m ago': '{count}분 전',
    '{count}h ago': '{count}시간 전',
    '{count}d ago': '{count}일 전',
    'yes': '예',
    'no': '아니요',
    'No blockers': '활성 차단 없음',
    'Blockers': '차단 항목',
    'enabled': '사용',
    'off': '사용 안 함',
    'No paths recorded.': '기록된 경로가 없습니다.',
    'No rows recorded.': '기록된 항목이 없습니다.',
    'No data loaded.': '불러온 데이터가 없습니다.',
    'missing': '누락',
    'Mock production': '예시 제작',
    'Safe mode': '안전 모드',
    'Safe mode · generation and upload blocked': '안전 모드 · 생성 및 업로드 차단',
    'View safety details': '안전 정책 상세 보기',
    'Electron bridge': 'Electron 브리지',
    'Mock fallback': '예시 데이터 대체 모드',
    'planning files': '계획 파일',
    'local reads/writes': '로컬 읽기·쓰기',
    'non-consuming status commands': '비소모 상태 명령',
    'image generation': '이미지 생성',
    'Dreamina submit': 'Dreamina 제출',
    'Gemini review': 'Gemini 검토',
    'external upload': '외부 업로드',
    'allowed': '허용',
    'preview only': '미리보기 전용',
    'blocked': '차단',
    'Files': '파일',
    'Pipeline file status': '파이프라인 파일 상태',
    'Parsed': '파싱',
    'Reviewed': '검토',
    'Accepted': '채택',
    'Planning file saved: {path}': '계획 파일을 저장했습니다: {path}',
    'Save blocked: {reason}': '저장이 차단되었습니다: {reason}',
    'Planning write safety policy rejected the request.': '안전한 계획 파일 경로와 내용인지 확인하세요.',
    'Folder selection blocked by the local path safety policy.': '로컬 경로 안전 정책에 따라 폴더 선택이 차단되었습니다.',
    'Local path safety policy blocked the request.': '로컬 경로 안전 정책에 따라 요청이 차단되었습니다.',

    // Intake
    'Start with a private Korean draft, or expand the selected production audit when needed.': '비공개 한글 초안으로 새 프로젝트를 시작하거나, 필요할 때 선택한 제작물 감사를 펼쳐 확인하세요.',
    'Start a new project': '새 프로젝트 시작',
    'Save the Korean brief and script as a local draft, then copy the fixed canonical builder command.': '한글 브리프와 스크립트를 로컬 초안으로 저장한 뒤, 고정된 canonical 빌더 명령을 복사하세요.',
    'Command ready': '명령 준비됨',
    'Draft only': '초안 전용',
    'Draft restored from this device.': '이 기기에 저장된 초안을 복원했습니다.',
    'Saving draft…': '초안 저장 중…',
    'Checking and copying command…': '명령을 다시 확인하고 복사하는 중…',
    'Draft could not be loaded safely.': '초안을 안전하게 불러오지 못했습니다.',
    'No saved new-project draft yet.': '아직 저장된 새 프로젝트 초안이 없습니다.',
    'production_id': '제작 ID',
    'brief': '브리프',
    'script': '스크립트',
    'route': '생성 경로',
    'aspect_ratio': '화면 비율',
    'scene_duration': '씬 길이(초)',
    'max_scenes': '최대 씬 수',
    'Use 3–64 lowercase letters, numbers, hyphens, or underscores.': '영문 소문자, 숫자, 하이픈, 밑줄만 사용해 3–64자로 입력하세요.',
    'Seedance': 'Seedance',
    'Flow/Omni': 'Flow/Omni',
    'Both routes': '두 경로 모두',
    'Choose which prompt package the canonical builder should prepare.': 'canonical 빌더가 준비할 프롬프트 패키지 경로를 선택하세요.',
    'Describe the concept, audience, tone, and non-negotiable requirements in Korean.': '콘셉트, 대상 시청자, 톤, 반드시 지킬 요구사항을 한글로 적으세요.',
    'Paste the final narration or dialogue script. It remains only in the private local draft.': '최종 내레이션 또는 대사 스크립트를 붙여 넣으세요. 비공개 로컬 초안에만 남습니다.',
    'Choose the final video frame.': '최종 영상의 화면 비율을 선택하세요.',
    '4–15 seconds per scene.': '씬당 4–15초로 설정하세요.',
    'Prepare 1–10 scenes.': '1–10개 씬을 준비할 수 있습니다.',
    'Saving…': '저장 중…',
    'Save local draft': '로컬 초안 저장',
    'Copy canonical build command': 'canonical 빌드 명령 복사',
    'Saving does not create a production or run a command. Run the copied command yourself outside this app, then refresh the production list.': '저장만으로 제작 폴더가 생기거나 명령이 실행되지 않습니다. 복사한 명령은 앱 밖에서 직접 실행한 뒤 제작 목록을 새로고침하세요.',
    'Configured production parent': '설정된 제작 상위 폴더',
    'Planned production folder': '예정 제작 폴더',
    'Canonical command preview': 'canonical 명령 미리보기',
    'Audit the selected production': '선택한 제작물 감사',
    'New project draft saved.': '새 프로젝트 초안을 저장했습니다.',
    'New project draft save was blocked.': '새 프로젝트 초안 저장이 차단되었습니다.',
    'Canonical build command copied.': 'canonical 빌드 명령을 복사했습니다.',
    'Canonical build command copy was blocked.': 'canonical 빌드 명령 복사가 차단되었습니다.',
    'NEW_PROJECT_DRAFT_EMPTY': '초안을 먼저 저장하세요.',
    'NEW_PROJECT_DRAFT_READ_FAILED': '초안 읽기 안전 검사를 통과하지 못했습니다.',
    'NEW_PROJECT_DRAFT_SAVE_FAILED': '초안 저장 안전 검사를 통과하지 못했습니다.',
    'NEW_PROJECT_COMMAND_COPY_FAILED': '명령 복사 안전 검사를 통과하지 못했습니다.',
    'NEW_PROJECT_USER_DATA_INVALID': 'Electron 초안 저장 위치를 안전하게 확인하지 못했습니다.',
    'NEW_PROJECT_DRAFT_DIRECTORY_UNSAFE': '초안 폴더가 안전한 비공개 폴더가 아닙니다.',
    'NEW_PROJECT_DRAFT_TARGET_UNSAFE': '기존 초안 저장 파일을 안전하게 확인하지 못했습니다.',
    'NEW_PROJECT_DRAFT_NOFOLLOW_UNAVAILABLE': '이 환경에서는 안전한 심볼릭 링크 차단을 사용할 수 없습니다.',
    'NEW_PROJECT_DRAFT_PARENT_CHANGED': '저장 중 초안 폴더가 변경되어 작업을 중단했습니다.',
    'NEW_PROJECT_DRAFT_TEMP_UNSAFE': '초안 임시 파일이 안전 검사를 통과하지 못했습니다.',
    'NEW_PROJECT_DRAFT_FILE_UNSAFE': '저장된 초안 파일이 안전 검사를 통과하지 못했습니다.',
    'NEW_PROJECT_DRAFT_FILE_CHANGED': '초안을 읽는 동안 파일이 변경되어 작업을 중단했습니다.',
    'NEW_PROJECT_DRAFT_INCOMPLETE': '저장된 초안 파일 일부가 누락되었습니다.',
    'NEW_PROJECT_DRAFT_METADATA_INVALID': '저장된 초안의 무결성 정보를 확인하지 못했습니다.',
    'NEW_PROJECT_DRAFT_METADATA_TOO_LARGE': '초안 무결성 정보가 허용 크기를 초과했습니다.',
    'NEW_PROJECT_DRAFT_SHAPE_INVALID': '새 프로젝트 입력 항목 구성이 올바르지 않습니다.',
    'NEW_PROJECT_ID_INVALID': '제작 ID 형식을 확인하세요.',
    'NEW_PROJECT_BRIEF_INVALID': '브리프를 입력하고 허용 크기 안인지 확인하세요.',
    'NEW_PROJECT_SCRIPT_INVALID': '스크립트를 입력하고 허용 크기 안인지 확인하세요.',
    'NEW_PROJECT_ROUTE_INVALID': '지원되는 생성 경로를 선택하세요.',
    'NEW_PROJECT_ASPECT_INVALID': '지원되는 화면 비율을 선택하세요.',
    'NEW_PROJECT_SCENE_DURATION_INVALID': '씬 길이는 4–15초로 입력하세요.',
    'NEW_PROJECT_MAX_SCENES_INVALID': '최대 씬 수는 1–10개로 입력하세요.',
    'NEW_PROJECT_PREVIEW_NOT_READY': 'canonical 빌드 명령을 아직 준비할 수 없습니다.',
    'NEW_PROJECT_CLIPBOARD_UNAVAILABLE': '시스템 클립보드를 사용할 수 없습니다.',
    'NEW_PROJECT_CLIPBOARD_VERIFY_FAILED': '복사한 명령을 클립보드에서 확인하지 못했습니다.',
    'NEW_PROJECT_PARENT_NOT_CONFIGURED': '설정에서 제작 상위 폴더를 먼저 선택하세요.',
    'NEW_PROJECT_PARENT_MISSING': '설정된 제작 상위 폴더가 없습니다.',
    'NEW_PROJECT_PARENT_UNSAFE': '제작 상위 폴더가 안전한 실제 폴더가 아닙니다.',
    'NEW_PROJECT_TARGET_FILE_EXISTS': '같은 제작 ID의 파일이 이미 있습니다.',
    'NEW_PROJECT_TARGET_SYMLINK': '같은 제작 ID의 심볼릭 링크가 이미 있습니다.',
    'NEW_PROJECT_TARGET_EMPTY_DIRECTORY_EXISTS': '같은 제작 ID의 빈 폴더가 이미 있습니다.',
    'NEW_PROJECT_TARGET_NONEMPTY_DIRECTORY_EXISTS': '같은 제작 ID의 제작 폴더가 이미 있습니다.',
    'NEW_PROJECT_TARGET_UNSAFE': '예정 제작 폴더를 안전하게 확인하지 못했습니다.',
    'NEW_PROJECT_HARNESS_NOT_READY': 'happyVideoFactory canonical 하네스가 준비되지 않았습니다.',
    'NEW_PROJECT_BUILDER_NOT_READY': '고정 canonical 빌더를 검증하지 못했습니다.',
    'FILM_PIPELINE_BRIDGE_UNAVAILABLE': 'Electron 앱에서만 로컬 초안을 저장할 수 있습니다.',
    'Production intent, route, media requirements, and stop-loss rule. This panel can save planning files only.': '제작 의도, 생성 경로, 미디어 요구사항과 중단 기준을 확인합니다. 이 화면은 계획 파일만 저장할 수 있습니다.',
    'Save planning file': '계획 파일 저장',
    'Brief valid': '브리프 유효',
    'No generation actions': '생성 작업 없음',
    'Project title': '프로젝트 제목',
    'Output folder': '출력 폴더',
    'Target route': '대상 경로',
    'Aspect ratio': '화면 비율',
    'Clip count': '클립 수',
    'Script path': '스크립트 경로',
    'Concept': '콘셉트',
    'Logline': '로그라인',
    'Stop-loss rule': '중단 기준',
    'Dialogue': '대사',
    'Subtitles': '자막',
    'Music': '음악',
    'Natural SFX': '자연 효과음',
    'Reference Media Paths': '참조 미디어 경로',

    // Storyboard and motion
    'Clip continuity packet with validator badges for dominant action, camera strategy, first-frame requirement, and continuity risk.': '주요 동작, 카메라 전략, 첫 프레임 요구사항과 연속성 위험을 클립별로 검토합니다.',
    'one dominant action': '주요 동작 지정',
    'dominant action missing': '주요 동작 누락',
    'one camera strategy': '카메라 전략 지정',
    'camera strategy missing': '카메라 전략 누락',
    'first-frame required': '첫 프레임 필요',
    'first-frame missing': '첫 프레임 누락',
    'continuity risk tracked': '연속성 위험 기록',
    'risk missing': '위험 기록 누락',
    'Scene': '씬',
    'Clip': '클립',
    'Duration': '길이',
    'Dramatic beat': '드라마 비트',
    'Characters': '등장인물',
    'Location': '장소',
    'First frame': '첫 프레임',
    'Action': '동작',
    'Camera': '카메라',
    'Lighting': '조명',
    'Audio/SFX/dialogue': '오디오·효과음·대사',
    'References': '참조',
    'Risk': '위험',
    'Validator badges': '검증 상태',
    'Shot cards used to lock movement, identity risk, and duration before submit preview.': '제출 미리보기 전에 카메라 움직임, 인물 일관성 위험과 길이를 샷별로 고정합니다.',
    'missing clip': '클립 누락',
    'duration lock': '길이 고정',
    'duration lock missing': '길이 고정 누락',
    'Shot size': '샷 크기',
    'Camera movement': '카메라 움직임',
    'Movement risk': '움직임 위험',
    'Identity risk': '인물 일관성 위험',
    'Continuity notes': '연속성 메모',

    // Assets, prompts, gates
    'Harness image dashboard mirror. Video submission remains blocked when required assets are RETRY, BLOCK, or UNREVIEWED without an explicit exception.': '하네스 이미지 대시보드를 읽기 전용으로 보여 줍니다. 필수 자산이 RETRY, BLOCK, UNREVIEWED이고 승인된 예외가 없으면 영상 제출은 계속 차단됩니다.',
    'dashboard current': '대시보드 최신',
    'dashboard blocked': '대시보드 차단',
    'content not parsed': '콘텐츠 파싱 안 됨',
    'content parsed or fixture': '콘텐츠 파싱 또는 예시 데이터',
    '{passed}/{total} image reviews pass/exception': '이미지 검토 통과·예외 {passed}/{total}',
    'Dashboard path': '대시보드 경로',
    'Dashboard updated': '대시보드 갱신 시각',
    'Dashboard parsed': '대시보드 파싱',
    'Dashboard stale': '대시보드 만료',
    'Submit-blocking assets': '제출 차단 자산',
    'Parse error': '파싱 오류',
    'No dashboard path recorded': '기록된 대시보드 경로 없음',
    'none': '없음',
    'Newer asset/review timestamps': '더 최신인 자산·검토 시각',
    'Asset': '자산',
    'Path': '경로',
    'Type': '유형',
    'Target shot': '대상 샷',
    'Prompt path': '프롬프트 경로',
    'Review path': '검토 경로',
    'Verdict': '판정',
    'Video-use status': '영상 사용 상태',
    'Retry notes': '재시도 메모',
    'Submit gate': '제출 게이트',
    'usable': '사용 가능',
    'Seedance and Flow prompt files, attached assets, prompt/media review state, and negative constraints.': 'Seedance·Flow 프롬프트 파일, 첨부 자산, 프롬프트·미디어 검토 상태와 네거티브 제약을 확인합니다.',
    'Generator': '생성기',
    'Prompt file': '프롬프트 파일',
    'Model': '모델',
    'Aspect': '비율',
    'Assets': '자산',
    'No BGM': '배경음악 없음',
    'Review': '검토',
    'required': '필수',
    'not locked': '고정 안 됨',
    'generator': '생성기',
    'no BGM locked': '배경음악 없음 고정',
    'music exception needed': '음악 예외 필요',
    'one camera movement per shot': '샷당 카메라 움직임 1개',
    'Negative Constraints': '네거티브 제약',
    'Every gate status must stay separate: pipeline pass is not output-quality acceptance.': '각 게이트 상태는 서로 분리해 판단합니다. 파이프라인 통과가 출력 품질 채택을 의미하지 않습니다.',
    'No gate record loaded.': '불러온 게이트 기록이 없습니다.',
    'Field': '필드',
    'Value': '값',

    // Queue
    'Submit and heartbeat ledgers. Live submit is disabled; UI-only mode only renders preview commands.': '제출과 하트비트 원장을 확인합니다. 라이브 제출은 차단되며 UI에는 명령 미리보기만 표시됩니다.',
    'No auto-retry': '자동 재시도 없음',
    'No duplicate jobs': '중복 작업 없음',
    'No VIP/fallback': 'VIP·대체 모델 없음',
    'Slow queue status is not a retry signal. Seedance/Dreamina clips get one live generation attempt by default; approved clips must be queued first with --poll=0, then heartbeat checks use only non-consuming list_task/query_result previews.': '느린 대기열 상태는 재시도 신호가 아닙니다. Seedance·Dreamina 클립은 기본적으로 라이브 생성 1회만 허용하며, 승인된 모든 클립을 --poll=0으로 먼저 대기열에 넣은 뒤 비소모 list_task/query_result 미리보기로만 하트비트를 확인합니다.',
    'Approved clips missing submit_id: {value}': '승인된 클립의 submit_id 누락: {value}',
    'Submitted records missing submit_id: {value}': '제출 기록의 submit_id 누락: {value}',
    'Duplicate live attempts blocked: {value}': '중복 라이브 시도 차단: {value}',
    'VIP/fallback evidence blocked: {value}': 'VIP·대체 모델 증거 차단: {value}',
    'Heartbeat blocked until all approved clips are queued with --poll=0: {value}': '모든 승인 클립을 --poll=0으로 대기열에 넣을 때까지 하트비트 차단: {value}',
    'Heartbeat not due: {value}': '아직 하트비트 시각이 아님: {value}',
    'Strict queue policy clear': '엄격 대기열 정책 통과',
    'No strict queue blocker is active for preview state.': '현재 미리보기 상태에는 엄격 대기열 차단이 없습니다.',
    'not recorded': '기록 없음',
    'submit_records.jsonl not loaded': 'submit_records.jsonl을 불러오지 못함',
    'heartbeat_log.jsonl not loaded': 'heartbeat_log.jsonl을 불러오지 못함',
    'Timeline': '진행 단계',
    'Submit ID': '제출 ID',
    'Live attempts': '라이브 시도',
    'Known credits': '확인된 크레딧',
    '{count} credits': '{count} 크레딧',
    'Backend model evidence': '백엔드 모델 증거',
    'Next heartbeat countdown': '다음 하트비트까지',
    'Downloaded files': '다운로드 파일',
    'Submitted?': '제출 여부',
    'missing submit_id': 'submit_id 누락',
    'Credits': '크레딧',
    'Next heartbeat': '다음 하트비트',
    'Submit disabled': '제출 차단',
    'Heartbeat preview only': '하트비트 미리보기 전용',
    'Heartbeat disabled until {time}': '{time}까지 하트비트 차단',
    '20m gate blocked': '20분 게이트 차단',
    '20m gate clear': '20분 게이트 통과',
    'Retry, faster queue, VIP/fallback model, and duplicate job paths are never suggested by this UI. Blocker: {blocker}.': '이 UI는 재시도, 빠른 대기열, VIP·대체 모델, 중복 작업 경로를 제안하지 않습니다. 차단 코드: {blocker}.',
    'Dreamina submit execution is not exposed. The cards below are shell-safe previews for planning, preflight/status, ffprobe, and concat review only.': 'Dreamina 제출 실행은 노출하지 않습니다. 아래 카드는 계획, 사전 점검·상태, ffprobe와 concat 검토를 위한 셸 안전 미리보기입니다.',
    'Dreamina submit execution is not exposed. Planning and status previews remain non-executing; unfinished ffprobe and selected-range rendering commands are blocked.': 'Dreamina 제출 실행은 노출하지 않습니다. 계획·상태 미리보기는 실행되지 않으며, 미완성 ffprobe와 선택 구간 렌더링 명령은 차단됩니다.',
    'Heartbeat Query Commands': '하트비트 조회 명령',
    'Copy-only Dreamina list_task/query_result previews. They remain disabled until submit_id is recorded, all approved clips are queued first, and the 20 minute gate is due.': 'Dreamina list_task/query_result를 복사 전용으로 미리 봅니다. submit_id가 기록되고 승인된 모든 클립이 먼저 대기열에 들어가며 20분 게이트 시각이 될 때까지 차단 상태를 유지합니다.',
    'Other Command Previews': '기타 명령 미리보기',
    'Planning, Dreamina help/user_credit, ffprobe, and concat cards are still copy-only; no hidden execution path is attached.': '계획, Dreamina help/user_credit, ffprobe, concat 카드도 복사 전용이며 숨은 실행 경로가 없습니다.',
    'Planning and Dreamina help/user_credit remain preview-only. ffprobe evidence and selected-range rendering cards are disabled and cannot be copied.': '계획과 Dreamina help/user_credit는 미리보기 전용입니다. ffprobe 증거와 선택 구간 렌더링 카드는 비활성화되어 복사할 수 없습니다.',
    'due now': '지금 확인 가능',
    '{minutes}m {seconds}s remaining': '{minutes}분 {seconds}초 남음',

    // QA and final
    'Clip QA, frame samples, contact sheets, and accepted seconds. Final is blocked until output quality is proven.': '클립 QA, 프레임 샘플, 콘택트 시트와 채택 구간을 확인합니다. 출력 품질이 입증될 때까지 최종 편집은 차단됩니다.',
    'ok': '통과',
    'Downloaded clips without QA records: {value}': 'QA 기록이 없는 다운로드 클립: {value}',
    'Accepted seconds source': '채택 구간 원본',
    'Canonical shot manifest': '정식 샷 매니페스트',
    'Canonical selected takes': '정식 선택 테이크',
    'Canonical QC report': '정식 QC 보고서',
    'Canonical QC is structural evidence only': '정식 QC는 구조 증거일 뿐임',
    'Human decision remains unreviewed': '사람의 최종 판정은 미검토',
    'Deterministic checks, external findings metadata, canonical decision, and human approval remain separate. A canonical accept decision does not prove final output quality.': '결정론적 검사, 외부 검토 메타데이터, 정식 판정, 사람의 승인은 서로 분리됩니다. 정식 accept 판정 하나만으로 최종 출력 품질이 입증되지는 않습니다.',
    'Canonical shot': '정식 샷',
    'Clip alias': '클립 별칭',
    'Provider': '제공자',
    'Deterministic checks': '결정론적 검사',
    'Dialogue score': '대사 명료도',
    'Pronunciation risk': '발음 위험',
    'risk detected': '위험 감지',
    'no risk flag': '위험 플래그 없음',
    'Canonical decision': '정식 판정',
    'External review metadata': '외부 검토 메타데이터',
    'Human decision': '사람 판정',
    'Overall QA': '종합 QA',
    'recorded_without_verdict': '기록 있음·판정 미확인',
    'missing_or_invalid': '누락 또는 무효',
    'accept': '선택',
    'retry': '재검토 필요',
    'abandon': '폐기',
    'Gemini frame review paths': 'Gemini 프레임 검토 경로',
    'Video review paths': '영상 검토 경로',
    'not loaded': '불러오지 않음',
    'Valid video': '유효한 영상',
    'Duration plausible': '길이 적합',
    'Identity': '인물 일관성',
    'First-frame role': '첫 프레임 일치',
    'No subtitles/logo/watermark/UI text': '자막·로고·워터마크·UI 문구 없음',
    'Continuity': '연속성',
    'Gemini frame review': 'Gemini 프레임 검토',
    'Video review': '영상 검토',
    'Whole clip is not automatically accepted': '전체 클립은 자동 채택되지 않음',
    'accepted ranges recorded': '채택 구간 기록됨',
    'accepted ranges with source evidence: {value}': '원본 증거가 있는 채택 구간: {value}',
    'Canonical ranges count only when shot identity is proven by shot_manifest.json, in/out values are finite, and the source is a real non-symlink file inside the selected production.': '정식 구간은 shot_manifest.json으로 샷 식별자가 입증되고, 시작·종료 값이 유한하며, 원본이 선택한 제작 폴더 내부의 실제 비심볼릭 파일일 때만 집계합니다.',
    'Accepted seconds must name explicit in/out ranges per clip. A downloaded or completed clip does not become accepted footage by default.': '채택 구간에는 클립별 시작·종료 시간을 명시해야 합니다. 다운로드 또는 생성 완료만으로 영상이 자동 채택되지는 않습니다.',
    'Source file': '원본 파일',
    'Source exists': '원본 존재',
    'Beat': '비트',
    'Take': '테이크',
    'Transition': '전환',
    'Provenance': '출처 계약',
    'In': '시작',
    'Out': '종료',
    'Range accepted?': '구간 채택 여부',
    'explicit range': '구간 지정',
    'not accepted': '채택 안 됨',
    'Reason': '사유',
    'Reviewer confidence': '검토 확신도',
    'canonical_selected_take': '정식 선택 테이크',
    'canonical_identifier_unproven': '정식 식별자 연결 미입증',
    'canonical_selected_take_invalid': '정식 선택 테이크 무효',
    'unsafe_source_path': '안전하지 않은 원본 경로',
    'symlink_source_path': '심볼릭 링크 원본 경로',
    'missing_source_file': '원본 파일 누락',
    'non_regular_source_file': '일반 파일이 아닌 원본',
    'non_directory_source_parent': '원본 상위 경로가 폴더가 아님',
    'Contact Sheets': '콘택트 시트',
    'Frame Samples': '프레임 샘플',
    'Gemini Frame Reviews': 'Gemini 프레임 검토',
    'Video Reviews': '영상 검토',
    'Final readiness checklist and exact blockers. Execution success is separated from output-quality proof.': '최종 준비 체크리스트와 정확한 차단 사유를 확인합니다. 실행 성공과 출력 품질 입증을 분리해 표시합니다.',
    'ready': '준비됨',
    'final ready': '최종 준비 완료',
    'evidence-only credits': '증거 기반 크레딧만 표시',
    'ffmpeg/ffprobe preview only': 'ffmpeg·ffprobe 미리보기 전용',
    'ffmpeg/ffprobe commands blocked': 'ffmpeg·ffprobe 명령 차단',
    'Final video exists: {path}': '최종 영상이 있습니다: {path}',
    'No final video exists. Current condition: {condition}.': '최종 영상이 없습니다. 현재 상태: {condition}.',
    'Final report path': '최종 보고서 경로',
    'Final video path': '최종 영상 경로',
    'Production folder': '제작 폴더',
    'Generator route': '생성 경로',
    'Concat list path': 'Concat 목록 경로',
    'ffprobe evidence path': 'ffprobe 증거 경로',
    'Delivery manifest path': 'Delivery manifest 경로',
    'Delivery SHA-256': 'Delivery SHA-256',
    'Persisted producer probe': '저장된 생산자 probe',
    'Fresh ffprobe status': '새 ffprobe 상태',
    'Fresh ffprobe evidence path': '새 ffprobe 증거 경로',
    '{duration}s · video and audio present': '{duration}초 · 영상·음성 스트림 있음',
    'not verified': '검증되지 않음',
    'verified': '검증됨',
    'not run': '실행하지 않음',
    'not available': '사용 불가',
    'Completion time': '완료 시각',
    'Residual risks': '잔여 위험',
    'Ready selected ranges': '사용 가능한 선택 구간',
    'Canonical QC records': '정식 QC 레코드',
    'Canonical clip alias proven': '정식 클립 별칭 입증됨',
    'Canonical clip alias blocked': '정식 클립 별칭 차단',
    'Canonical final readiness not proven': '정식 최종 준비 상태 미입증',
    'Canonical delivery evidence verified': '정식 delivery 증거 검증됨',
    'Canonical delivery evidence not verified': '정식 delivery 증거 미검증',
    'Fresh ffprobe verified': '새 ffprobe 검증됨',
    'Fresh ffprobe not run': '새 ffprobe 실행 안 함',
    'delivery hash verified': 'delivery 해시 검증됨',
    'A verified delivery manifest proves only the canonical master file, its persisted producer probe, and delivery stitch evidence. It does not prove human QA, selected coverage, submit or download history, report presence, or output quality.': '검증된 delivery manifest는 정식 마스터 파일, 저장된 생산자 probe, delivery 편집 증거만 입증합니다. 사람 QA, 선택 구간 충족, 제출·다운로드 이력, 보고서 존재, 출력 품질은 입증하지 않습니다.',
    'Selected ranges and canonical QC are finishing inputs, not a rendered final. Final readiness still requires matching planned clip identities, passed QA or an explicit exception, final.mp4, report, concat evidence, and real ffprobe evidence.': '선택 구간과 정식 QC는 마감 입력이지 렌더된 최종본이 아닙니다. 최종 준비에는 계획 클립 식별자 일치, QA 통과 또는 명시적 예외, final.mp4, 보고서, concat 증거, 실제 ffprobe 증거가 모두 필요합니다.',
    'First-frame image': '첫 프레임 이미지',
    'Prompt pack path': '프롬프트 팩 경로',
    'Status': '상태',
    'Model evidence': '모델 증거',
    'Downloaded file': '다운로드 파일',
    'QA verdict': 'QA 판정',
    'Accepted seconds': '채택 구간',
    'Checked at': '확인 시각',
    'Queue status': '대기열 상태',
    'Gen status': '생성 상태',
    'Blocker': '차단 코드',
    'Final Stitch Command Previews': '최종 편집 명령 미리보기',
    'Copy-only previews for ffmpeg concat and ffprobe validation. These commands are not executed by the UI.': 'ffmpeg concat과 ffprobe 검증 명령을 복사 전용으로 미리 봅니다. UI는 이 명령을 실행하지 않습니다.',
    'Final command safety status': '최종 명령 안전 상태',
    'ffprobe evidence persistence and selected-range rendering are not implemented, so both command cards are disabled and cannot be copied.': 'ffprobe 증거 저장과 선택 구간 렌더링이 구현되지 않아 두 명령 카드 모두 비활성화되며 복사할 수 없습니다.',
    'The app does not run a fresh ffprobe or render selected ranges. Both command cards remain disabled and cannot be copied, even when persisted delivery evidence is verified.': '앱은 새 ffprobe를 실행하거나 선택 구간을 렌더링하지 않습니다. 저장된 delivery 증거가 검증되어도 두 명령 카드는 비활성화되며 복사할 수 없습니다.',
    'Readiness details': '준비 상태 상세',
    'Blockers and residual risks': '차단 항목과 잔여 위험',
    'blockers recorded empty': '기록된 차단 없음',
    'all clips downloaded': '모든 클립 다운로드',
    'all QA passed or exception recorded': '모든 QA 통과 또는 예외 기록',
    'accepted seconds recorded': '채택 구간 기록',
    'concat list exists': 'concat 목록 존재',
    'verified delivery stitch evidence': '검증된 delivery 편집 증거',
    'verified canonical master exists': '검증된 정식 마스터 존재',
    'persisted producer probe verified': '저장된 생산자 probe 검증',
    'final.mp4 exists': 'final.mp4 존재',
    'ffprobe verification exists': 'ffprobe 검증 존재',
    'report.md exists': 'report.md 존재',
    'not available · {condition}': '사용 불가 · {condition}',
    'not complete': '미완료',
    'confidence not recorded': '확신도 기록 없음',
    'queued': '대기열 진행 중',
    'blocked before submission': '제출 전 차단',
    'generated but failed QA': '생성 완료 후 QA 실패',
    'missing download': '다운로드 누락',
    'missing accepted seconds': '채택 구간 누락',
    'missing final stitch': '최종 편집 누락',

    // Shot designer and supporting previews
    'Preview-only shot payload builder adapted from the old Video and Cinema Studio control patterns. No generation, upload, or external review is wired.': '샷 페이로드를 미리보기 전용으로 구성합니다. 생성, 업로드, 외부 검토 기능은 연결되어 있지 않습니다.',
    'Model target': '대상 모델',
    'Copy Shot Payload JSON': '샷 페이로드 JSON 복사',
    'Save to storyboard draft': '스토리보드 초안에 저장',
    'Copied': '복사됨',
    'Copy failed': '복사 실패',
    'Copy DeepSearchTeam prompt': 'DeepSearchTeam 프롬프트 복사',
    'Save DeepSearchTeam prompt draft': 'DeepSearchTeam 프롬프트 초안 저장',
    'ShotPayload draft': 'ShotPayload 초안',
    'No hosted API calls': '호스팅 API 호출 없음',
    'No submit jobs': '제출 작업 없음',
    'Planning file only': '계획 파일 전용',
    'Prompt And Output Shape': '프롬프트와 출력 구조',
    'Model is UI metadata only. The emitted JSON uses the ShotPayload contract fields.': '모델 선택은 UI 메타데이터입니다. 출력 JSON은 ShotPayload 계약 필드를 그대로 사용합니다.',
    'Prompt': '프롬프트',
    'Audio / SFX / Dialogue': '오디오·효과음·대사',
    'Risk Notes': '위험 메모',
    'ShotPayload JSON': 'ShotPayload JSON',
    'copy/save only': '복사·저장 전용',
    'DeepSearchTeam Scene Image Prompt': 'DeepSearchTeam 장면 이미지 프롬프트',
    'Storyboard-to-scene image route. Profile {profile}, Thinking mode, one finished image only. Execution remains blocked in this UI.': '스토리보드 기반 장면 이미지 경로입니다. 프로필 {profile}, Thinking 모드, 완성 이미지 1장만 사용하며 이 UI에서는 실행이 차단됩니다.',
    'goldpure369 required': 'goldpure369 필요',
    'Thinking mode required': 'Thinking 모드 필요',
    'one image only': '이미지 1장만',
    'no generation run': '생성 실행 없음',
    'Camera Controls': '카메라 설정',
    'Local shot metadata only. These controls never submit a render job.': '로컬 샷 메타데이터만 편집합니다. 이 설정은 렌더 작업을 제출하지 않습니다.',
    'payload only': '페이로드 전용',
    'Lens': '렌즈',
    'Focal length': '초점 거리',
    'Aperture': '조리개',
    'Movement': '움직임',
    'Media References': '미디어 참조',
    'Displays existing local stills and references. There is no upload, generation, or external review.': '기존 로컬 스틸 이미지와 참조 자료를 표시합니다. 업로드, 생성, 외부 검토는 없습니다.',
    'local display only': '로컬 표시 전용',
    'End frame': '마지막 프레임',
    '{count} selected': '{count}개 선택',
    'Paste local reference path only. No upload or read occurs.': '로컬 참조 경로만 붙여 넣으세요. 업로드나 파일 읽기는 실행되지 않습니다.',
    'Local reference path': '로컬 참조 경로',
    'Add local path': '로컬 경로 추가',
    'No path recorded': '기록된 경로 없음',
    'Set first frame': '첫 프레임으로 지정',
    'Set end frame': '마지막 프레임으로 지정',
    'Add reference': '참조 추가',
    'Selected References': '선택한 참조',
    'Remove': '제거',
    'History And Preview Grid': '기록과 미리보기',
    'Preview-only grid for local references, downloaded evidence, and current payload JSON.': '로컬 참조, 다운로드 증거와 현재 페이로드 JSON을 미리보기 전용으로 표시합니다.',
    'no run controls': '실행 컨트롤 없음',
    'Current ShotPayload': '현재 ShotPayload',
    'reference asset': '참조 자산',
    '{clip} downloaded file': '{clip} 다운로드 파일',
    'No previewable media path recorded.': '미리 볼 수 있는 미디어 경로가 기록되지 않았습니다.',
    'Automatic media preview unavailable.': '자동 미디어 미리보기를 사용할 수 없습니다.',
    'Only explicit local media sources are previewed. The recorded path remains available below.': '명시적인 로컬 미디어 소스만 미리 봅니다. 기록된 경로는 아래에서 계속 확인할 수 있습니다.',
    'Preview unavailable': '미리보기 불가',
    'reference preview': '참조 미리보기',
    'Shot preview': '샷 미리보기',
    'payload draft': '페이로드 초안',
    'Close preview': '미리보기 닫기',
    '{ } Payload': '{ } 페이로드',
    'Video Preview': '영상 미리보기',
    'Open Preview': '미리보기 열기',
    'No preview or history items recorded yet.': '아직 미리보기 또는 기록 항목이 없습니다.',
    'Command preview': '명령 미리보기',
    'Build pipeline plan': '파이프라인 계획 만들기',
    'Run contract-only pipeline': '계약 전용 파이프라인 미리보기',
    'Canonical pack build': 'Canonical pack 만들기',
    'Canonical pack validate': 'Canonical pack 검증',
    'Dreamina help': 'Dreamina 도움말',
    'Dreamina user_credit': 'Dreamina 크레딧 조회',
    'Dreamina list_task help': 'Dreamina list_task 도움말',
    'Dreamina query_result help': 'Dreamina query_result 도움말',
    'Dreamina list_task': 'Dreamina 작업 목록 조회',
    'Dreamina query_result': 'Dreamina 결과 조회',
    'ffprobe validation': 'ffprobe 검증',
    'ffmpeg concat preview': 'ffmpeg concat 미리보기',
    'DeepSearchTeam scene image': 'DeepSearchTeam 장면 이미지',
    'Preview card only. No run button is rendered.': '미리보기 카드만 제공합니다. 실행 버튼은 표시하지 않습니다.',
    'Copy command': '명령 복사',
    'Copy unavailable': '복사 불가',
    'required evidence output': '필수 증거 출력',
    'blocker if disabled': '비활성화 시 차단 코드',
    'None': '없음',
    'DeepSearchTeam dst image is a ChatGPT image-generation side effect. This UI may copy the prompt or command preview only; execution requires a later explicit approval gate.': 'DeepSearchTeam dst image는 ChatGPT 이미지 생성 부작용이 있습니다. 이 UI에서는 프롬프트나 명령 미리보기만 복사할 수 있으며, 실행에는 이후 별도의 명시적 승인이 필요합니다.',

    // Settings panel
    'Local pipeline paths and dry-run controls. Dry-run mode is locked on by default.': '로컬 파이프라인 경로와 드라이런 제어를 관리합니다. 드라이런 모드는 항상 켜진 상태로 잠깁니다.',
    'Production parent': '제작 상위 폴더',
    'The folder that contains all productions (immediate subdirs are listed in the sidebar).': '모든 제작 폴더를 포함한 상위 폴더입니다. 바로 아래 폴더가 제작 목록에 표시됩니다.',
    'Browse parent': '상위 폴더 선택',
    'Refresh': '새로고침',
    'Production root': '현재 제작 루트',
    'Shorts harness doc': 'Shorts 하네스 문서',
    'Seedance harness doc': 'Seedance 하네스 문서',
    'Dreamina CLI path': 'Dreamina CLI 경로',
    'Flow/Omni setting': 'Flow·Omni 설정',
    'placeholder only': '자리표시자 전용',
    'ffmpeg path': 'ffmpeg 경로',
    'ffprobe path': 'ffprobe 경로',
    'Model directories': '모델 폴더',
    'Dry-run mode': '드라이런 모드',
    'Locked ON. Live generation, external review, submit, and upload paths are not available in this UI shell.': '항상 켜짐으로 잠겨 있습니다. 이 UI에는 라이브 생성, 외부 검토, 제출, 업로드 경로가 없습니다.',
    'planning files allowed': '계획 파일 허용',
    'status commands preview only': '상태 명령 미리보기 전용',
    'generation blocked': '생성 차단',
    'external upload blocked': '외부 업로드 차단',
    'ON': '켜짐',
    'Canonical harness handoff': 'Canonical 하네스 연결',
    'happyVideoFactory canonical contract': 'happyVideoFactory canonical 계약',
    'Available': '사용 가능',
    'Partial': '부분',
    'Blocked': '차단',
    'Read-only metadata': '읽기 전용 메타데이터',
    'The canonical pack validator is available as a copy-only local read preview.': 'Canonical pack validator를 복사 전용 로컬 읽기 미리보기로 사용할 수 있습니다.',
    'Canonical pack commands remain copy-disabled until the fixed-root contract is complete.': '고정 루트 계약이 완전해질 때까지 canonical pack 명령 복사는 차단됩니다.',
    'The main process checks only the fixed allowlist. File content and renderer-provided harness paths are not accepted.': 'main process는 고정 allowlist만 검사합니다. 파일 내용과 renderer가 전달한 하네스 경로는 받지 않습니다.',
    'File': '파일',
});

export function pipelineText(source, replacements = {}) {
    const template = getLang() === 'ko-KR' ? (KO[source] || source) : source;
    return String(template).replace(/\{([a-zA-Z0-9_]+)\}/g, (match, key) => (
        Object.prototype.hasOwnProperty.call(replacements, key) ? String(replacements[key]) : match
    ));
}

export const p = pipelineText;
