export const BLOCKERS = Object.freeze({
    MISSING_PIPELINE_DOC: 'MISSING_PIPELINE_DOC',
    MISSING_WORK_DECOMPOSITION: 'MISSING_WORK_DECOMPOSITION',
    MISSING_PRODUCTION_BRIEF: 'MISSING_PRODUCTION_BRIEF',
    MISSING_STORYBOARD_CONTINUITY_PACKET: 'MISSING_STORYBOARD_CONTINUITY_PACKET',
    MISSING_MOTION_BOARD: 'MISSING_MOTION_BOARD',
    MISSING_YOUMIND_TEMPLATE_EVIDENCE: 'MISSING_YOUMIND_TEMPLATE_EVIDENCE',
    MISSING_GPT_IMAGE_GUIDE_EVIDENCE: 'MISSING_GPT_IMAGE_GUIDE_EVIDENCE',
    IMAGE_PROMPT_TEMPLATE_NOT_REVIEWED: 'IMAGE_PROMPT_TEMPLATE_NOT_REVIEWED',
    IMAGE_GEMINI_REVIEW_REQUIRED: 'IMAGE_GEMINI_REVIEW_REQUIRED',
    IMAGE_GEMINI_REVIEW_NOT_PASS: 'IMAGE_GEMINI_REVIEW_NOT_PASS',
    MISSING_IMAGE_DASHBOARD: 'MISSING_IMAGE_DASHBOARD',
    IMAGE_DASHBOARD_STALE: 'IMAGE_DASHBOARD_STALE',
    MISSING_REFERENCE_ANNOTATION: 'MISSING_REFERENCE_ANNOTATION',
    MISSING_VIDEO_REFERENCE_METADATA: 'MISSING_VIDEO_REFERENCE_METADATA',
    DURATION_LOCK_MISSING: 'DURATION_LOCK_MISSING',
    DREAMINA_PREFLIGHT_BLOCKED: 'DREAMINA_PREFLIGHT_BLOCKED',
    GEMINI_REVIEW_BLOCKED: 'GEMINI_REVIEW_BLOCKED',
    FRAME_EXTRACTION_BLOCKED: 'FRAME_EXTRACTION_BLOCKED',
    GEMINI_VIDEO_REVIEW_BLOCKED: 'GEMINI_VIDEO_REVIEW_BLOCKED',
    CREDIT_CONFIRMATION_REQUIRED: 'CREDIT_CONFIRMATION_REQUIRED',
    MODEL_MISMATCH: 'MODEL_MISMATCH',
    MISSING_ACCEPTED_SECONDS: 'MISSING_ACCEPTED_SECONDS',
    OUTPUT_QUALITY_NOT_PROVEN: 'OUTPUT_QUALITY_NOT_PROVEN',
});

export const BLOCKER_LIST = Object.freeze(Object.values(BLOCKERS));

export function isKnownBlocker(blocker) {
    return BLOCKER_LIST.includes(blocker);
}

export function normalizeBlocker(blocker) {
    return isKnownBlocker(blocker) ? blocker : BLOCKERS.DREAMINA_PREFLIGHT_BLOCKED;
}
